### PR TITLE
Bump minor version for ESLint 2.x release

### PR DESCRIPTION
**Pull request by justinhelmer**
Please `npm publish` So I can submit a pull request for [#6](https://github.com/google/eslint-config-google/issues/6).

Thank you! 🦄

### CODE REVIEW

**Comment by justinhelmer** [comment]
I'm really unclear why bumping the package version would cause the [esnext tests](https://travis-ci.org/sindresorhus/eslint-config-xo/jobs/108958422#L200) to fail, _only_ for `node 0.10`.

I have submitted an alternative pull request #14 that only bumps the **patch** version instead of the **minor** version if you prefer. The entire [test suite](https://travis-ci.org/sindresorhus/eslint-config-xo/builds/108959525) passes for the alternative PR.

**Comment by shinnn** [comment]
https://twitter.com/sindresorhus/status/298376330544824320

**Comment by justinhelmer** [comment]
@shinnn @sindresorhus Thanks! I'm very new to open source. Will never happen again.

Cheers.

**Comment by shinnn** [comment]
@justinhelmer Most Node.js developers have their favorite npm-publish tools that run tests, bump version in `package.json`, create a Git tag, push to remote, and publish a new version to npm automatically.

The author of this project always uses his own awesome tool. https://github.com/sindresorhus/np

**Comment by justinhelmer** [comment]
Darn! [npm-publish-release](https://github.com/justinhelmer/npm-publish-release) 

If I just talked to you first, @shinnn, I could have saved some time of writing my own ;-)

I appreciate your willingness to teach a man interested in obtaining knowledge.

**Pull request closed without merging**
