### PR TITLE
Add support for HTML / Vue component

### PR DESCRIPTION
**Pull request by gucong3000**
After a few days used, I think `XO` is great, But most of our projects use Vue.
So i need to compatible with Vue component.

### CODE REVIEW

**Comment by kevva** [comment]
Why don't you just extend the `xo` config in your project?

```json
//package.json
{
	devDependencies: {
		"eslint-plugin-html": "*"
	},
	"xo": {
		"plugins": [
			"html"
		]
	}
}
```

**Comment by sindresorhus** [comment]
You could create a shareable config for Vue, ala https://github.com/sindresorhus/eslint-config-xo-react

**Comment by gucong3000** [comment]
If i want `xo` support vue by default, without config, what should I do?

**Comment by sindresorhus** [comment]
@gucong3000 I'm not interested in having support for Vue by default in XO. That's a slippery slope. Then everyone will want support for their framework. You can easily do something like https://github.com/sindresorhus/eslint-config-xo-react and just have it in the `extends` XO package.json config.

**Comment by gucong3000** [comment]
It is a very cool thing that `xo` can use without config. It is not easy for some pople in our trem to config `package.json`. that is why I like `xo`

**Comment by sindresorhus** [comment]
If you create a Vue config, all you need in your package.json is:

```js
"xo": {
	"extends": ["vue-config-name"]
}
```

**Comment by gucong3000** [comment]
Yes, it is so easy to you and me, but for most front-end developer, there is to much tools need to study. In our work flow, we have 6 linter: eclint, stylelint, eslint, jshint, jscc, csslint. we have 3 build tool: webpack, gulp, grunt. they are  all need config.

**Pull request closed without merging**
